export const INITIAL_STATE = 'INITIAL_STATE';

export const REQUEST_FETCH_FLIGHTS = 'REQUEST_FETCH_FLIGHTS';
export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';
export const FETCH_FLIGHTS_ERROR = 'FETCH_FLIGHTS_ERROR';

export const CREATE_FLIGHT = 'CREATE_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';